name: covid-json

# 触发条件
on:
  schedule:
    - cron: '3 0 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  updateJson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wget json
        run: wget -O echarts/covid-sg-data.json https://infographics.channelnewsasia.com/covid-19/sgsitrepv2.json
      - name: stage change files
        run: git add echarts/covid-sg-data.json
      - name: commit
        run: |
          git config --global user.email "action@github.local"
          git config --global user.name "action"
          git commit -m "auto update data.json"
      - name: push
        run: git push origin HEAD:main
